--------------------------------------------------------
--  File created - Tuesday-August-30-2022   
--------------------------------------------------------
@C:\PMS\PMS Dev Files\Source\Indexes\DROP.sql
@C:\PMS\PMS Dev Files\Source\Indexes\DEMO_ORDER_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\LGS_CONTRACTS_INNN.sql
@C:\PMS\PMS Dev Files\Source\Indexes\CSS_TASK_IND.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_CONTRACT_STAGES_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_ENROLLED_DETS_IND_F.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_WBS_I2.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_WBS_OUTCOMES_I2.sql
@C:\PMS\PMS Dev Files\Source\Indexes\CITIZEN_EVENTS_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRCS_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\OBAT_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\CSS_MOD_IND.sql
@C:\PMS\PMS Dev Files\Source\Indexes\DEMO_CUST_NAME_IX.sql
@C:\PMS\PMS Dev Files\Source\Indexes\XLIB_LOGS_IDX1.sql
@C:\PMS\PMS Dev Files\Source\Indexes\LGS_LOGOS_BRANCHES_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_CURRENCY_RATES_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\WRKTYP_UK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\XLIB_LOGS_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\TIMR_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\EXPE_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\DEMO_ORDER_ITEMS_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PROJ_CONT_FK_I.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_PIPELINE_MODULES_INDEX1.sql
@C:\PMS\PMS Dev Files\Source\Indexes\XLIB_LOGS_IDX2.sql
@C:\PMS\PMS Dev Files\Source\Indexes\LGS_CONTRACT_DOCS_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\OPP_ROLES_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\MYIMAGES_TBL_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\CSS_EMP_IND.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_WBS_ASSIGNEES_WBA_ID_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\CONT_COMP_FK_I.sql
@C:\PMS\PMS Dev Files\Source\Indexes\WRKTYP_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_WBS_ASSIGNEES_I3.sql
@C:\PMS\PMS Dev Files\Source\Indexes\OPP_ACTION_STAKEHOLDERS_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_WBS_OUTCOMES_WBO_ID_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_ESTIMATED_DETS_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_WBS_DOCS_I2.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_EMPLOYEE_SKILLS_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_GROUPS_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\FMSG_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_WBS_DEPENDENCIES_I3.sql
@C:\PMS\PMS Dev Files\Source\Indexes\GRDPR_UK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\OPP_ACTIONS_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\OPP_STATUS_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_STATUS_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\OPP_ROLE_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_WBS_ROW_KEY_UNQ.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_CONTRACT_SUMMARY_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_OFFER_STATUS_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_WBS_DEPENDENCI_ROW_KEY_UNQ.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_WBS_DOCS_WBC_ID_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\SALGRD_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_EXPENCES_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\CONN_UK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\DEMO_IMAGES_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\SALGRD_GRDPR_FK_I.sql
@C:\PMS\PMS Dev Files\Source\Indexes\HISTORY_IDX1.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_WBS_ASSIGNEES_I4.sql
@C:\PMS\PMS Dev Files\Source\Indexes\DEMO_PAGE_HIERARCHY_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_CONTRACT_TYPES_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_WBS_DEPENDENCIES_I1.sql
@C:\PMS\PMS Dev Files\Source\Indexes\DEMO_USERS_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_WBS_DEPENDENCIES_I2.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PROJ_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\HISTORY_IDX2.sql
@C:\PMS\PMS Dev Files\Source\Indexes\OBJT_UK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\OPP_PRESALE_ACTIVITIES_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\DGRM_UK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_WBS_I1.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_OUTCOME_TYPES_POT_ID_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\DEMO_CUSTOMERS_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_GROUP_EMPLOYEES_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_WBS_DEPENDENCI_WBD_ID_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\GRDPR_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_PRWKTP_DET_STATUS_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\XLIB_COMPONENTS_U01.sql
@C:\PMS\PMS Dev Files\Source\Indexes\OPP_CONTACTS_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\EMPSAL_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\DISPLAY_ORDER_UK1.sql
@C:\PMS\PMS Dev Files\Source\Indexes\SBFL_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_INVOICES_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\EXPR_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\CFIG_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_ENROLLED_DETS_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_PROJECT_STATUS_HISTORY_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_WBS_OUTCOMES_I1.sql
@C:\PMS\PMS Dev Files\Source\Indexes\DEMO_PRODUCT_INFO_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\CONT_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_ESTIMATED_DETS_IND_F1.sql
@C:\PMS\PMS Dev Files\Source\Indexes\OPP_SCOPE_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_WBS_OUTCOMES_ROW_KEY_UNQ.sql
@C:\PMS\PMS Dev Files\Source\Indexes\TIMR_PRCS_SBFL_IX.sql
@C:\PMS\PMS Dev Files\Source\Indexes\CSS_TEMP_COMPANIES_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_WBS_DOCS_I1.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_WBS_ASSIGNEES_I2.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_WBS_DOCS_ROW_KEY_UNQ.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_LVL_USAGE_TYPE_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\XLIB_COMPONENTS_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\EXPR_UK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\DEMO_ORD_CUSTOMER_IX.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_CURRENCIES_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJWORK_WRKTYP_FK_I.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_PRWKTP_DET_TYPES_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\CONN_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\CSS_TEMP_MODULES_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\STAGES_STATUS_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\EMPSAL_SALGRD_FK_I.sql
@C:\PMS\PMS Dev Files\Source\Indexes\INDEX1.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_WBS_ASSIGNEES_ROW_KEY_UNQ.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_WBS_WBS_ID_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\OBJT_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\CSS_COMP_IND.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_ESTIMATED_DETS_IND11.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_EXPENCE_TYPES_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\OPP_STAGES.sql
@C:\PMS\PMS Dev Files\Source\Indexes\CSS_TEMP_TASKS_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_INTERNAL_CLASSIFICATIO_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\MYIMAGES_COLLECTION_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\OPPORTUNITIES_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\DGRM_UK2.sql
@C:\PMS\PMS Dev Files\Source\Indexes\CSS_TASK_COMP_MOD.sql
@C:\PMS\PMS Dev Files\Source\Indexes\OPP_ACTION_STAKEHOLDERS_ACTION.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PROV_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJWORK_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\OPP_ACTIONS_DOCS_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJ_OUTCOME_TYPES_ROW_KEY_UNQ.sql
@C:\PMS\PMS Dev Files\Source\Indexes\DGRM_PK.sql
@C:\PMS\PMS Dev Files\Source\Indexes\PRJWORK_PROJ_FK_I.sql
