--------------------------------------------------------
--  DDL for Index PRJWORK_WRKTYP_FK_I
--------------------------------------------------------

  CREATE INDEX "PRJ"."PRJWORK_WRKTYP_FK_I" ON "PRJ"."PRJ_PROJECTWORK_TYPES" ("WRKTYP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 917504 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
