--------------------------------------------------------
--  File created - Tuesday-August-30-2022   
--------------------------------------------------------
@C:\PMS\PMS Dev Files\Source\Views\DROP.sql
@C:\PMS\PMS Dev Files\Source\Views\COMPANIES.sql
@C:\PMS\PMS Dev Files\Source\Views\CONTRACT_WORK.sql
@C:\PMS\PMS Dev Files\Source\Views\EXPE_P0001_1_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\EXPE_P0001_2_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\EXPE_P0001_3_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\EXPE_P0002_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\EXPE_P0003_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\EXPE_P0004_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\EXPE_P0005_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\EXPE_P0006_ARCHIVE_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\EXPE_P0006_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\EXPE_P0007_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\EXPE_P0008_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\EXPE_P0010_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\EXPE_P10060_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_DIAGRAMS_PARSED_LOV.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_DIAGRAMS_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_DIAGRAM_CATEGORIES_LOV.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_INSTANCES_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_INSTANCE_CONNECTIONS_LOV.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_INSTANCE_DETAILS_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_INSTANCE_GATEWAYS_LOV.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_INSTANCE_VARIABLES_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_P0002_DIAGRAMS_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_P0007_INSTANCES_COUNTER_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_P0008_INSTANCE_DETAILS_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_P0008_INSTANCE_LOG_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_P0008_SUBFLOWS_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_P0008_VARIABLES_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_P0008_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_P0010_INSTANCES_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_P0010_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_P0013_ATTRIBUTES_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_P0013_EXPRESSIONS_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_P0013_INSTANCE_LOG_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_P0013_STEP_LOG_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_P0013_SUBFLOWS_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_P0013_VARIABLE_LOG_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_P0014_INSTANCE_LOG_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_P0014_STEP_LOG_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_P0014_SUBFLOWS_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_P0014_VARIABLE_LOG_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_SUBFLOWS_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\FLOW_TASK_INBOX_VW.sql
@C:\PMS\PMS Dev Files\Source\Views\HISTORY_V.sql
@C:\PMS\PMS Dev Files\Source\Views\PRJ_CLIENT_CONTACTS.sql
@C:\PMS\PMS Dev Files\Source\Views\PRJ_COMPANIES.sql
@C:\PMS\PMS Dev Files\Source\Views\SECURITY_GROUPS.sql
@C:\PMS\PMS Dev Files\Source\Views\prj_areas.sql
