--------------------------------------------------------
--  DDL for View PRJ_CLIENT_CONTACTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PRJ"."PRJ_CLIENT_CONTACTS" ("CODE", "COMPANY", "FIRST_NAME", "FATHER_NAME", "FAMILY_NAME", "A_FIRST_NAME", "A_FATHER_NAME", "A_FAMILY_NAME", "GENDER", "NATIONALITY", "POSITION_CODE", "POSITION_DESC", "DIRECT_TELEPHONE", "DIRECT_FAX", "EMAIL", "MAIL_POST_ADDRESS", "MAILINGLIST_GROUP", "PORTAL_USER_NAME", "PASSWD", "USER_ROLE", "INT_CODE", "TOBECHECKED", "WHO_ENTERED", "DATE_ENTERED", "APEX_USER", "MAKE_PUBLIC", "MODULE_CODE", "COMMENTS", "PRJ_CODE", "ESUPPORT_CODE", "SALES_PERSON_CODE", "SALES_USERS_CODE") AS 
  SELECT 
    "CODE","COMPANY","FIRST_NAME","FATHER_NAME","FAMILY_NAME","A_FIRST_NAME","A_FATHER_NAME","A_FAMILY_NAME","GENDER","NATIONALITY","POSITION_CODE","POSITION_DESC","DIRECT_TELEPHONE","DIRECT_FAX","EMAIL","MAIL_POST_ADDRESS","MAILINGLIST_GROUP","PORTAL_USER_NAME","PASSWD","USER_ROLE","INT_CODE","TOBECHECKED","WHO_ENTERED","DATE_ENTERED","APEX_USER","MAKE_PUBLIC","MODULE_CODE","COMMENTS","PRJ_CODE","ESUPPORT_CODE","SALES_PERSON_CODE","SALES_USERS_CODE"
FROM 
    LOGOS.LGS_PERSON;
