--------------------------------------------------------
--  DDL for View PRJ_COMPANIES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PRJ"."PRJ_COMPANIES" ("CODE", "DSP_CODE", "E_NAME", "A_NAME", "COUNTRY", "AREA_CODE", "MAIN_TELEPHONE", "HOME_PAGE", "MAIN_FAX", "POBOX", "PRIMARY_PERSON", "HOMEPAGE", "OWNER_COMPANY", "COMPANY_DESC", "CUSTOMER", "BUS_TYPE", "PARENT_COMPANY", "PARTNER", "CHECKED", "MOBILE", "EMAIL", "COMPETITOR", "DELETED", "SALES_CODE", "PRJ_CODE", "ESUPPORT_CODE") AS 
  select "CODE","DSP_CODE","E_NAME","A_NAME","COUNTRY","AREA_CODE","MAIN_TELEPHONE","HOME_PAGE","MAIN_FAX","POBOX","PRIMARY_PERSON","HOMEPAGE","OWNER_COMPANY","COMPANY_DESC","CUSTOMER","BUS_TYPE","PARENT_COMPANY","PARTNER","CHECKED","MOBILE","EMAIL","COMPETITOR","DELETED","SALES_CODE","PRJ_CODE","ESUPPORT_CODE" from PRJ_COMPANIES_SYN;
