--------------------------------------------------------
--  DDL for View SECURITY_GROUPS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PRJ"."SECURITY_GROUPS" ("PGR_ID", "PGR_CODE", "PGE_ID", "EMP_CODE", "EMP_NAME", "EMP_TITLE") AS 
  SELECT
  PRJ_GROUPS.PGR_ID,
  PRJ_GROUPS.PGR_CODE,
  PRJ_GROUP_EMPLOYEES.PGE_ID,
  PRJ_EMPLOYEE_SALARY.EMP_CODE,
  PRJ_EMPLOYEE_SALARY.EMP_NAME,
  PRJ_EMPLOYEE_SALARY.EMP_TITLE
FROM
  PRJ_GROUPS
INNER JOIN PRJ_GROUP_EMPLOYEES
ON
  PRJ_GROUPS.PGR_ID = PRJ_GROUP_EMPLOYEES.PGE_PGR_ID
INNER JOIN PRJ_EMPLOYEE_SALARY
ON
  PRJ_EMPLOYEE_SALARY.EMP_CODE = PRJ_GROUP_EMPLOYEES.PGE_EMPLOYEE;
