--------------------------------------------------------
--  File created - Tuesday-August-30-2022   
--------------------------------------------------------
@C:\PMS\PMS Dev Files\Source\Sequences\DROP.sql
@C:\PMS\PMS Dev Files\Source\Sequences\BM_PSH_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\CITIZEN_EVENTS_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\CSS_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\DEMO_CUST_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\DEMO_IMAGES_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\DEMO_ORDER_ITEMS_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\DEMO_ORD_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\DEMO_PROD_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\DEMO_USERS_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\DEPT_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\EMP_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\EST_TYPES_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\HISTORY_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\LGS_CONTRACTS_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\LGS_LCD_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\LGS_PROJECTS_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\NEXMO_SMS_RESPONSE_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\OPP_OAC_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\OPP_OAD_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\OPP_OAS_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\OPP_OCN_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\OPP_OPA_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\OPP_OPR_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\OPP_OPS_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\OPP_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_COMPANIES_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_COMPANY_CONTRACTS_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_CONTRACT_STAGES_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_CONTRACT_SUMMARY_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_CONTRACT_TYPES_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_CURRENCIES_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_CURRENCY_RATES_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_DURATION_UOM_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_EMPLOYEE_SALARY_HISTORY_S.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_EMPLOYEE_SALARY_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_EMPLOYEE_SKILLS_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_ENROLLED_DETS_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_ENROLLED_FILES_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_ESTIMATED_DETS_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_EXPENCES_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_EXPENCE_TYPES_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_GRADE_PRICES_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_INVOICES_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_MODULES_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_PGE_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_PPM_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_PROJECTWORK_TYPES_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_PROJECT_TEMPLATES_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_PROJECT_TEMPLATE_DETS_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_PRWKTP_DETS_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_PRWKTP_DET_STATUS_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_PRWKTP_DET_TYPES_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_SALARY_GRADES_HISTORY_S.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_SALARY_GRADES_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_TASKS_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_USER_CONTRACTS_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PRJ_WORK_TYPES_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\PROJECT_EMPLOYEE_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\ROL_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\ROW_KEY_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\TEMP_WT.sql
@C:\PMS\PMS Dev Files\Source\Sequences\WORK_TYPE_GROUPS_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Sequences\XLIB_SEQ.sql
