--------------------------------------------------------
--  DDL for Sequence PRJ_EMPLOYEE_SALARY_HISTORY_S
--------------------------------------------------------

   CREATE SEQUENCE  "PRJ"."PRJ_EMPLOYEE_SALARY_HISTORY_S"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 2021 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
