--------------------------------------------------------
--  DDL for Sequence PRJ_PROJECT_TEMPLATE_DETS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRJ"."PRJ_PROJECT_TEMPLATE_DETS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
