--------------------------------------------------------
--  File created - Tuesday-September-06-2022   
--------------------------------------------------------
@Z:\PMS\Dev\App 222\Pages\1._Home.sql
@Z:\PMS\Dev\App 222\Pages\2._test.sql
@Z:\PMS\Dev\App 222\Pages\3._WebAPI.sql
@Z:\PMS\Dev\App 222\Pages\4._jawad_activiti_rest_api.sql
@Z:\PMS\Dev\App 222\Pages\5._SET_THEME.sql
@Z:\PMS\Dev\App 222\Pages\6._test_if_modal_dialogue.sql
@Z:\PMS\Dev\App 222\Pages\7._copy_of_page_121_-_jawad.sql
@Z:\PMS\Dev\App 222\Pages\8._google_map_integration_with_apex.sql
@Z:\PMS\Dev\App 222\Pages\9._Open_Street_Map.sql
@Z:\PMS\Dev\App 222\Pages\10._TASKS.sql
@Z:\PMS\Dev\App 222\Pages\11._CREATE_TASK.sql
@Z:\PMS\Dev\App 222\Pages\12._PRJ_WBS_ASSIGNEE.sql
@Z:\PMS\Dev\App 222\Pages\13._PRJ_WBS_ASSIGNEE_EDIT.sql
@Z:\PMS\Dev\App 222\Pages\14._geolocation_api.sql
@Z:\PMS\Dev\App 222\Pages\15._leaflet_map.sql
@Z:\PMS\Dev\App 222\Pages\16._PRJ_WBS_DEPENDENCIES.sql
@Z:\PMS\Dev\App 222\Pages\17._PRJ_WBS_DEPENDENCIES_EDIT.sql
@Z:\PMS\Dev\App 222\Pages\18._Lebanon_Map_Automatic_page.sql
@Z:\PMS\Dev\App 222\Pages\19._WBS_WB_DOCS_UPLOAD.sql
@Z:\PMS\Dev\App 222\Pages\20._WBS_WB_DOCS_UPLOAD_EDIT.sql
@Z:\PMS\Dev\App 222\Pages\21._DOWNLOAD.sql
@Z:\PMS\Dev\App 222\Pages\22._FILE_UPLOAD.sql
@Z:\PMS\Dev\App 222\Pages\23._DISPLAY_TREE.sql
@Z:\PMS\Dev\App 222\Pages\24._dropzone_js_-__Nick_Buytaert.sql
@Z:\PMS\Dev\App 222\Pages\25._DOWNLOAD_ONE_IMAGE_TEST.sql
@Z:\PMS\Dev\App 222\Pages\26._chuck_upload_hidden_collection_region.sql
@Z:\PMS\Dev\App 222\Pages\27._lebanon_map.sql
@Z:\PMS\Dev\App 222\Pages\28._Tree_Page.sql
@Z:\PMS\Dev\App 222\Pages\29._alaska_map.sql
@Z:\PMS\Dev\App 222\Pages\30._copy_from_page_14.sql
@Z:\PMS\Dev\App 222\Pages\31._Outcome.sql
@Z:\PMS\Dev\App 222\Pages\32._Edit_Outcome.sql
@Z:\PMS\Dev\App 222\Pages\33._Similirities.sql
@Z:\PMS\Dev\App 222\Pages\34._Edit_Similarities.sql
@Z:\PMS\Dev\App 222\Pages\35._test.sql
@Z:\PMS\Dev\App 222\Pages\36._Pipeline.sql
@Z:\PMS\Dev\App 222\Pages\37._openstreetmap_copy_page_14_-_2.sql
@Z:\PMS\Dev\App 222\Pages\38._chunk_upload_images.sql
@Z:\PMS\Dev\App 222\Pages\39._DOWNLOAD_ONE_IMAGE_in_IR.sql
@Z:\PMS\Dev\App 222\Pages\40._Contracts.sql
@Z:\PMS\Dev\App 222\Pages\41._chunk_upload_images_using_collection.sql
@Z:\PMS\Dev\App 222\Pages\42._copy_of_page_41.sql
@Z:\PMS\Dev\App 222\Pages\43._test_download_image.sql
@Z:\PMS\Dev\App 222\Pages\44._copy_of_page_42.sql
@Z:\PMS\Dev\App 222\Pages\45._SPA.sql
@Z:\PMS\Dev\App 222\Pages\46._Report.sql
@Z:\PMS\Dev\App 222\Pages\47._Efforts.sql
@Z:\PMS\Dev\App 222\Pages\48._Remaining_Effort.sql
@Z:\PMS\Dev\App 222\Pages\49._Statistics.sql
@Z:\PMS\Dev\App 222\Pages\50._Information.sql
@Z:\PMS\Dev\App 222\Pages\79._Pipeline_-_Edit.sql
@Z:\PMS\Dev\App 222\Pages\101._PMS_-_Log_In.sql
@Z:\PMS\Dev\App 222\Pages\102._storm_petrel_multi_factor_auth.sql
