--------------------------------------------------------
--  File created - Tuesday-August-30-2022   
--------------------------------------------------------
@C:\PMS\PMS Dev Files\Source\Packages\DROP.sql
@C:\PMS\PMS Dev Files\Source\Packages\APEXTRAS_YUBICO.sql
@C:\PMS\PMS Dev Files\Source\Packages\CSS_CUSTOMER_API.sql
@C:\PMS\PMS Dev Files\Source\Packages\CSS_ISRF_API.sql
@C:\PMS\PMS Dev Files\Source\Packages\CSS_PCK.sql
@C:\PMS\PMS Dev Files\Source\Packages\CSS_PROJECTS.sql
@C:\PMS\PMS Dev Files\Source\Packages\CSS_TO_CONT.sql
@C:\PMS\PMS Dev Files\Source\Packages\EXPE_CONSTANTS.sql
@C:\PMS\PMS Dev Files\Source\Packages\EXPE_FLOW_EXPENSECLAIMS.sql
@C:\PMS\PMS Dev Files\Source\Packages\EXPE_P0002.sql
@C:\PMS\PMS Dev Files\Source\Packages\EXPE_P0006.sql
@C:\PMS\PMS Dev Files\Source\Packages\EXPE_ROLES.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_API_PKG.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_BOUNDARY_EVENTS.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_BPMN_PARSER_PKG.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_CONSTANTS_PKG.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_DIAGRAM.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_ENGINE.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_ENGINE_APP_API.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_ENGINE_UTIL.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_ERRORS.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_EXPRESSIONS.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_GATEWAYS.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_GLOBALS.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_INSTANCES.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_LOGGING.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_MIGRATE_XML_PKG.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_MODELER.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_P0010_API.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_PLSQL_RUNNER_PKG.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_PLUGIN_MANAGE_INSTANCE.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_PLUGIN_MANAGE_INSTANCE_STEP.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_PLUGIN_MANAGE_INSTANCE_VARIABLES.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_PROCESS_VARS.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_RESERVATIONS.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_SERVICES.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_TASKS.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_THEME_API.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_TIMERS_PKG.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_TYPES_PKG.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_USERTASK_PKG.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_VIEWER.sql
@C:\PMS\PMS Dev Files\Source\Packages\LDAP_GLOBALS.sql
@C:\PMS\PMS Dev Files\Source\Packages\LGS_CONTRACTS_PCK.sql
@C:\PMS\PMS Dev Files\Source\Packages\NEXMO_PKG.sql
@C:\PMS\PMS Dev Files\Source\Packages\PRJ_OO_PCK.sql
@C:\PMS\PMS Dev Files\Source\Packages\PRJ_OUTCOME_TYPES_API.sql
@C:\PMS\PMS Dev Files\Source\Packages\PRJ_WBS_API.sql
@C:\PMS\PMS Dev Files\Source\Packages\PRJ_WBS_ASSIGNEES_API.sql
@C:\PMS\PMS Dev Files\Source\Packages\PRJ_WBS_DEPENDENCIES_API.sql
@C:\PMS\PMS Dev Files\Source\Packages\PRJ_WBS_DOCS_API.sql
@C:\PMS\PMS Dev Files\Source\Packages\PRJ_WBS_OUTCOMES_API.sql
@C:\PMS\PMS Dev Files\Source\Packages\PRJ_WEB_PCK.sql
@C:\PMS\PMS Dev Files\Source\Packages\PROJECT_PARAM.sql
@C:\PMS\PMS Dev Files\Source\Packages\PROJECT_PCK.sql
@C:\PMS\PMS Dev Files\Source\Packages\SHOW_HIDE_MEMORY.sql
@C:\PMS\PMS Dev Files\Source\Packages\TOTP_PKG.sql
@C:\PMS\PMS Dev Files\Source\Packages\TRANSFER_DATA.sql
@C:\PMS\PMS Dev Files\Source\Packages\TWOFACTOR.sql
@C:\PMS\PMS Dev Files\Source\Packages\TWOFACTOR_ADMIN.sql
@C:\PMS\PMS Dev Files\Source\Packages\TWOFACTOR_INTERNAL.sql
@C:\PMS\PMS Dev Files\Source\Packages\UPDATE_COMPANY_CODES.sql
@C:\PMS\PMS Dev Files\Source\Packages\VLT_MFA_PKG.sql
@C:\PMS\PMS Dev Files\Source\Packages\XLIB_COMPONENT.sql
@C:\PMS\PMS Dev Files\Source\Packages\XLIB_HTTP.sql
@C:\PMS\PMS Dev Files\Source\Packages\XLIB_JASPERREPORTS.sql
@C:\PMS\PMS Dev Files\Source\Packages\XLIB_LOG.sql
@C:\PMS\PMS Dev Files\Source\Packages\CSS_CUSTOMER_API_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\CSS_ISRF_API_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\CSS_PCK_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\CSS_PROJECTS_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\CSS_TO_CONT_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\EXPE_FLOW_EXPENSECLAIMS_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\EXPE_P0002_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\EXPE_P0006_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\EXPE_ROLES_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_API_PKG_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_BOUNDARY_EVENTS_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_BPMN_PARSER_PKG_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_DIAGRAM_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_ENGINE_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_ENGINE_APP_API_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_ENGINE_UTIL_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_ERRORS_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_EXPRESSIONS_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_GATEWAYS_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_GLOBALS_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_INSTANCES_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_LOGGING_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_MIGRATE_XML_PKG_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_MODELER_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_P0010_API_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_PLSQL_RUNNER_PKG_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_PLUGIN_MANAGE_INSTANCE_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_PLUGIN_MANAGE_INSTANCE_STEP_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_PLUGIN_MANAGE_INSTANCE_VARIABLES_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_PROCESS_VARS_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_RESERVATIONS_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_SERVICES_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_TASKS_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_THEME_API_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_TIMERS_PKG_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_USERTASK_PKG_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\FLOW_VIEWER_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\LGS_CONTRACTS_PCK_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\NEXMO_PKG_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\PRJ_OUTCOME_TYPES_API_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\PRJ_WBS_API_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\PRJ_WBS_ASSIGNEES_API_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\PRJ_WBS_DEPENDENCIES_API_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\PRJ_WBS_DOCS_API_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\PRJ_WBS_OUTCOMES_API_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\PRJ_WEB_PCK_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\PROJECT_PARAM_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\PROJECT_PCK_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\SHOW_HIDE_MEMORY_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\TOTP_PKG_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\TRANSFER_DATA_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\TWOFACTOR_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\TWOFACTOR_ADMIN_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\TWOFACTOR_INTERNAL_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\UPDATE_COMPANY_CODES_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\VLT_MFA_PKG_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\XLIB_COMPONENT_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\XLIB_HTTP_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\XLIB_JASPERREPORTS_1.sql
@C:\PMS\PMS Dev Files\Source\Packages\XLIB_LOG_1.sql
