--------------------------------------------------------
--  File created - Tuesday-August-30-2022   
--------------------------------------------------------
@C:\PMS\PMS Dev Files\Source\Triggers\DROP.sql
@C:\PMS\PMS Dev Files\Source\Triggers\APEX_TEAM_DEV_FILES_BIU.sql
@C:\PMS\PMS Dev Files\Source\Triggers\BI_DEMO_USERS.sql
@C:\PMS\PMS Dev Files\Source\Triggers\BI_PRJ_INVOICES.sql
@C:\PMS\PMS Dev Files\Source\Triggers\CITIZEN_REPORTS_BIU.sql
@C:\PMS\PMS Dev Files\Source\Triggers\CSS_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\DEMO_ORDER_ITEMS_GET_PRICE.sql
@C:\PMS\PMS Dev Files\Source\Triggers\DEMO_USERS_T1.sql
@C:\PMS\PMS Dev Files\Source\Triggers\DEPT_TRG1.sql
@C:\PMS\PMS Dev Files\Source\Triggers\EMP_TRG1.sql
@C:\PMS\PMS Dev Files\Source\Triggers\EST_TYPES_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\INSERT_DEMO_CUST.sql
@C:\PMS\PMS Dev Files\Source\Triggers\INSERT_DEMO_ORDER_ITEMS.sql
@C:\PMS\PMS Dev Files\Source\Triggers\INSERT_DEMO_PROD.sql
@C:\PMS\PMS Dev Files\Source\Triggers\LGS_CONTRACTS_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\LGS_PROJECTS_SEQ.sql
@C:\PMS\PMS Dev Files\Source\Triggers\LGS_PROJECTS__AFTERINS_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_COMPANY_CONTRACTS_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_CONTRACT_STAGES_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_CONTRACT_SUMMARY_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_CONTRACT_TYPES_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_CURRENCIES_2_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_CURRENCIES_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_CURRENCY_RATES_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_DURATION_UOM_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_EMPLOYEE_SALARY_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_EMPLOYEE_SKILLS_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_ENROLLED_DETS_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_ENROLLED_FILES_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_ESTIMATED_DETS_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_EXPENCES_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_EXPENCE_TYPES_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_GRADE_PRICES.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_GRADE_PRICES_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_OUTCOME_TYPES_BIU.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_PROJECTWORK_TYPES_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_PROJECT_TEMPLATES_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_PROJECT_TEMPLATE_DETS_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_PRWKTP_DET_STATUS_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_PRWKTP_DET_TYPES_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_SALARY_GRADES_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_TASKS_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_USER_CONTRACTS_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_WBS_ASSIGNEES_BIU.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_WBS_AUD.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_WBS_BIU.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_WBS_DEPENDENCIES_BIU.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_WBS_DOCS_BIU.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_WBS_OUTCOMES_BIU.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PRJ_WORK_TYPES_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PROJECT_EMPLOYEE_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\PSH_SEND_EMAIL_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\TRIGGER1.sql
@C:\PMS\PMS Dev Files\Source\Triggers\UPDATEPROJECTSTATUS.sql
@C:\PMS\PMS Dev Files\Source\Triggers\UPDATE_ORDER_TOTAL.sql
@C:\PMS\PMS Dev Files\Source\Triggers\WORK_TYPE_GROUPS_TRG.sql
@C:\PMS\PMS Dev Files\Source\Triggers\XLIB_LOGS_BI_TRG.sql
