--------------------------------------------------------
--  DDL for Trigger PSH_SEND_EMAIL_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PRJ"."PSH_SEND_EMAIL_TRG" 
AFTER INSERT OR UPDATE OF PSH_DATE,PSH_ID,PSH_PRJ_ID,PSH_STS_ID ON PRJ_PROJECT_STATUS_HISTORY 
REFERENCING OLD AS OLD NEW AS NEW 
BEGIN
  -- SELECT PST_SEND_EMAIL_FLG INTO FLG FROM PRJ_STATUS WHERE PST_ID = :NEW.PSH_STS_ID;
  -- IF(:NEW.PSH_DATE <> :OLD.PSH_DATE OR :NEW.PSH_STS_ID <> :OLD.PSH_STS_ID) THEN
  -- IF UPPER(FLG) = 'Y' THEN
    --SEND EMAIL
    --UTL_EMAIL.SEND_EMAIL();
    --END IF;
    --END IF;
    NULL;
END;

/
ALTER TRIGGER "PRJ"."PSH_SEND_EMAIL_TRG" ENABLE;
