--------------------------------------------------------
--  DDL for Table CONTRACTS
--------------------------------------------------------

  CREATE TABLE "PRJ"."CONTRACTS" 
   (	"ID" NUMBER(8,0), 
	"CONTRACT" VARCHAR2(15 BYTE), 
	"COMPANY" VARCHAR2(135 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"TYPE" VARCHAR2(75 BYTE), 
	"STAGE" VARCHAR2(75 BYTE), 
	"FINALISED" VARCHAR2(3 BYTE), 
	"ESTIMATE" NUMBER, 
	"VALUE" NUMBER(19,0), 
	"EXPENCES" NUMBER, 
	"ENROLLMENT" NUMBER, 
	"NET" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
