--------------------------------------------------------
--  DDL for Index CSS_TASK_COMP_MOD
--------------------------------------------------------

  CREATE INDEX "PRJ"."CSS_TASK_COMP_MOD" ON "PRJ"."CSS" ("TASK", "COMP", "MOD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 393216 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
