--------------------------------------------------------
--  DDL for Table CSS_PROJECT_TASKS
--------------------------------------------------------

  CREATE TABLE "PRJ"."CSS_PROJECT_TASKS" 
   (	"SERIAL" NUMBER(6,0), 
	"SCHEDULE_DATE" DATE, 
	"PERSONNEL_CODE" VARCHAR2(150 BYTE), 
	"PERSONNEL_NAME" VARCHAR2(75 BYTE), 
	"PERSONNEL_ACTIVE_FLG" VARCHAR2(1 BYTE), 
	"CUSTOMER_CODE" VARCHAR2(150 BYTE), 
	"CUSTOMER_NAME" VARCHAR2(150 BYTE), 
	"LOCATION" VARCHAR2(15 BYTE), 
	"TASK_CODE" VARCHAR2(150 BYTE), 
	"TASK_DESC" VARCHAR2(240 BYTE), 
	"PROJECT_CODE" VARCHAR2(150 BYTE), 
	"MODULE_CODE" VARCHAR2(150 BYTE), 
	"MODULE_NAME" VARCHAR2(75 BYTE), 
	"LABOUR_HOURS" NUMBER, 
	"DESCRIPTION" VARCHAR2(250 BYTE), 
	"TOBECHECKED" VARCHAR2(1 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 50331648 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
