--------------------------------------------------------
--  DDL for Table DELETED_COMPANIES
--------------------------------------------------------

  CREATE TABLE "PRJ"."DELETED_COMPANIES" 
   (	"CODE" VARCHAR2(125 CHAR), 
	"NAME" VARCHAR2(4000 CHAR), 
	"TO_COMPANY" VARCHAR2(125 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
