--------------------------------------------------------
--  DDL for Index DGRM_UK2
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRJ"."DGRM_UK2" ON "PRJ"."FLOW_DIAGRAMS" ("DGRM_NAME", CASE "DGRM_STATUS" WHEN 'released' THEN NULL ELSE "DGRM_VERSION" END ) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
