--------------------------------------------------------
--  DDL for Table EMPLOYEE_IMAGE
--------------------------------------------------------

  CREATE TABLE "PRJ"."EMPLOYEE_IMAGE" 
   (	"ID" NUMBER(10,0), 
	"EMPLOYEE_ID" NUMBER(6,0), 
	"MIMETYPE" VARCHAR2(50 BYTE), 
	"FILENAME" VARCHAR2(50 BYTE), 
	"IMAGE_LAST_UPDATE_DATE" DATE, 
	"IMAGE" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("IMAGE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
