--------------------------------------------------------
--  DDL for Index EXPR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRJ"."EXPR_PK" ON "PRJ"."FLOW_OBJECT_EXPRESSIONS" ("EXPR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
