--------------------------------------------------------
--  DDL for Table FLOW_FLOW_EVENT_LOG
--------------------------------------------------------

  CREATE TABLE "PRJ"."FLOW_FLOW_EVENT_LOG" 
   (	"LGFL_DGRM_ID" NUMBER, 
	"LGFL_DGRM_NAME" VARCHAR2(150 CHAR), 
	"LGFL_DGRM_VERSION" VARCHAR2(10 CHAR), 
	"LGFL_DGRM_STATUS" VARCHAR2(10 CHAR), 
	"LGFL_DGRM_CATEGORY" VARCHAR2(30 CHAR), 
	"LGFL_TIMESTAMP" TIMESTAMP (6) WITH TIME ZONE, 
	"LGFL_USER" VARCHAR2(255 CHAR), 
	"LGFL_COMMENT" VARCHAR2(2000 CHAR), 
	"LGFL_DGRM_CONTENT" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("LGFL_DGRM_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
