--------------------------------------------------------
--  DDL for Table FLOW_INSTANCE_EVENT_LOG
--------------------------------------------------------

  CREATE TABLE "PRJ"."FLOW_INSTANCE_EVENT_LOG" 
   (	"LGPR_PRCS_ID" NUMBER, 
	"LGPR_OBJT_ID" VARCHAR2(50 CHAR), 
	"LGPR_DGRM_ID" NUMBER, 
	"LGPR_PRCS_NAME" VARCHAR2(150 CHAR), 
	"LGPR_BUSINESS_ID" VARCHAR2(4000 CHAR), 
	"LGPR_PRCS_EVENT" VARCHAR2(20 CHAR), 
	"LGPR_TIMESTAMP" TIMESTAMP (6) WITH TIME ZONE, 
	"LGPR_USER" VARCHAR2(255 CHAR), 
	"LGPR_COMMENT" VARCHAR2(2000 CHAR), 
	"LGPR_ERROR_INFO" VARCHAR2(2000 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
