--------------------------------------------------------
--  DDL for Table FLOW_PROCESSES
--------------------------------------------------------

  CREATE TABLE "PRJ"."FLOW_PROCESSES" 
   (	"PRCS_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PRCS_DGRM_ID" NUMBER, 
	"PRCS_NAME" VARCHAR2(150 CHAR), 
	"PRCS_STATUS" VARCHAR2(20 CHAR), 
	"PRCS_INIT_TS" TIMESTAMP (6) WITH TIME ZONE, 
	"PRCS_LAST_UPDATE" TIMESTAMP (6) WITH TIME ZONE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
