--------------------------------------------------------
--  DDL for Table FLOW_SUBFLOWS
--------------------------------------------------------

  CREATE TABLE "PRJ"."FLOW_SUBFLOWS" 
   (	"SBFL_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SBFL_PRCS_ID" NUMBER, 
	"SBFL_DGRM_ID" NUMBER, 
	"SBFL_SBFL_ID" NUMBER, 
	"SBFL_PROCESS_LEVEL" NUMBER, 
	"SBFL_STARTING_OBJECT" VARCHAR2(50 CHAR), 
	"SBFL_ROUTE" VARCHAR2(100 CHAR), 
	"SBFL_LAST_COMPLETED" VARCHAR2(50 CHAR), 
	"SBFL_CURRENT" VARCHAR2(50 CHAR), 
	"SBFL_STEP_KEY" VARCHAR2(20 CHAR), 
	"SBFL_STATUS" VARCHAR2(20 CHAR), 
	"SBFL_BECAME_CURRENT" TIMESTAMP (6) WITH TIME ZONE, 
	"SBFL_WORK_STARTED" TIMESTAMP (6) WITH TIME ZONE, 
	"SBFL_HAS_EVENTS" VARCHAR2(200 CHAR), 
	"SBFL_RESERVATION" VARCHAR2(255 CHAR), 
	"SBFL_LAST_UPDATE" TIMESTAMP (6) WITH TIME ZONE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
