--------------------------------------------------------
--  DDL for Table FLOW_STEP_EVENT_LOG
--------------------------------------------------------

  CREATE TABLE "PRJ"."FLOW_STEP_EVENT_LOG" 
   (	"LGSF_PRCS_ID" NUMBER, 
	"LGSF_OBJT_ID" VARCHAR2(50 BYTE), 
	"LGSF_SBFL_ID" NUMBER, 
	"LGSF_SBFL_PROCESS_LEVEL" NUMBER, 
	"LGSF_LAST_COMPLETED" VARCHAR2(50 BYTE), 
	"LGSF_STATUS_WHEN_COMPLETE" VARCHAR2(20 BYTE), 
	"LGSF_SBFL_DGRM_ID" NUMBER, 
	"LGSF_WAS_CURRENT" TIMESTAMP (6) WITH TIME ZONE, 
	"LGSF_STARTED" TIMESTAMP (6) WITH TIME ZONE, 
	"LGSF_COMPLETED" TIMESTAMP (6) WITH TIME ZONE, 
	"LGSF_RESERVATION" VARCHAR2(255 CHAR), 
	"LGSF_USER" VARCHAR2(255 CHAR), 
	"LGSF_COMMENT" VARCHAR2(2000 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
