--------------------------------------------------------
--  DDL for Table FLOW_VARIABLE_EVENT_LOG
--------------------------------------------------------

  CREATE TABLE "PRJ"."FLOW_VARIABLE_EVENT_LOG" 
   (	"LGVR_PRCS_ID" NUMBER, 
	"LGVR_VAR_NAME" VARCHAR2(50 CHAR), 
	"LGVR_OBJT_ID" VARCHAR2(50 CHAR), 
	"LGVR_SBFL_ID" NUMBER, 
	"LGVR_EXPR_SET" VARCHAR2(20 CHAR), 
	"LGVR_TIMESTAMP" TIMESTAMP (6) WITH TIME ZONE, 
	"LGVR_VAR_TYPE" VARCHAR2(50 CHAR), 
	"LGVR_VAR_VC2" VARCHAR2(4000 CHAR), 
	"LGVR_VAR_NUM" NUMBER, 
	"LGVR_VAR_DATE" DATE, 
	"LGVR_VAR_CLOB" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("LGVR_VAR_CLOB") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
