--------------------------------------------------------
--  DDL for Table FLOW_SUBFLOW_LOG
--------------------------------------------------------

  CREATE TABLE "PRJ"."FLOW_SUBFLOW_LOG" 
   (	"SFLG_PRCS_ID" NUMBER, 
	"SFLG_OBJT_ID" VARCHAR2(50 BYTE), 
	"SFLG_SBFL_ID" NUMBER, 
	"SFLG_LAST_UPDATED" DATE, 
	"SFLG_NOTES" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
