--------------------------------------------------------
--  File created - Tuesday-August-30-2022   
--------------------------------------------------------
@C:\PMS\PMS Dev Files\Source\Tables\DROP.sql
@C:\PMS\PMS Dev Files\Source\Tables\APEX_TEAM_DEV_FILES.sql
@C:\PMS\PMS Dev Files\Source\Tables\CITIZEN_EVENTS.sql
@C:\PMS\PMS Dev Files\Source\Tables\CLIENT_IMAGE_DESKTOP.sql
@C:\PMS\PMS Dev Files\Source\Tables\CONTRACTS.sql
@C:\PMS\PMS Dev Files\Source\Tables\CSS.sql
@C:\PMS\PMS Dev Files\Source\Tables\CSS_PERSONNEL_ENROLL_PER_YEAR.sql
@C:\PMS\PMS Dev Files\Source\Tables\CSS_PERSONNEL_ROLE_YEAR.sql
@C:\PMS\PMS Dev Files\Source\Tables\CSS_PROJECT_TASKS.sql
@C:\PMS\PMS Dev Files\Source\Tables\CSS_REFERESHED_ON.sql
@C:\PMS\PMS Dev Files\Source\Tables\CSS_TEMP_COMPANIES.sql
@C:\PMS\PMS Dev Files\Source\Tables\CSS_TEMP_MODULES.sql
@C:\PMS\PMS Dev Files\Source\Tables\CSS_TEMP_TASKS.sql
@C:\PMS\PMS Dev Files\Source\Tables\DELETED_COMPANIES.sql
@C:\PMS\PMS Dev Files\Source\Tables\DELETED_MODULES.sql
@C:\PMS\PMS Dev Files\Source\Tables\DEMO_CUSTOMERS.sql
@C:\PMS\PMS Dev Files\Source\Tables\DEMO_IMAGES.sql
@C:\PMS\PMS Dev Files\Source\Tables\DEMO_ORDERS.sql
@C:\PMS\PMS Dev Files\Source\Tables\DEMO_ORDER_ITEMS.sql
@C:\PMS\PMS Dev Files\Source\Tables\DEMO_PAGE_HIERARCHY.sql
@C:\PMS\PMS Dev Files\Source\Tables\DEMO_PRODUCT_INFO.sql
@C:\PMS\PMS Dev Files\Source\Tables\DEMO_STATES.sql
@C:\PMS\PMS Dev Files\Source\Tables\DEMO_USERS.sql
@C:\PMS\PMS Dev Files\Source\Tables\DEPT.sql
@C:\PMS\PMS Dev Files\Source\Tables\EMP.sql
@C:\PMS\PMS Dev Files\Source\Tables\EMPLOYEE_IMAGE.sql
@C:\PMS\PMS Dev Files\Source\Tables\EMPLOYEE_IMAGE_JAWAD.sql
@C:\PMS\PMS Dev Files\Source\Tables\EST_TYPES.sql
@C:\PMS\PMS Dev Files\Source\Tables\EXPE_EXPENSES.sql
@C:\PMS\PMS Dev Files\Source\Tables\FLOW_CONFIGURATION.sql
@C:\PMS\PMS Dev Files\Source\Tables\FLOW_CONNECTIONS.sql
@C:\PMS\PMS Dev Files\Source\Tables\FLOW_DIAGRAMS.sql
@C:\PMS\PMS Dev Files\Source\Tables\FLOW_FLOW_EVENT_LOG.sql
@C:\PMS\PMS Dev Files\Source\Tables\FLOW_INSTANCE_EVENT_LOG.sql
@C:\PMS\PMS Dev Files\Source\Tables\FLOW_MESSAGES.sql
@C:\PMS\PMS Dev Files\Source\Tables\FLOW_OBJECTS.sql
@C:\PMS\PMS Dev Files\Source\Tables\FLOW_OBJECT_ATTRIBUTES.sql
@C:\PMS\PMS Dev Files\Source\Tables\FLOW_OBJECT_EXPRESSIONS.sql
@C:\PMS\PMS Dev Files\Source\Tables\FLOW_PROCESSES.sql
@C:\PMS\PMS Dev Files\Source\Tables\FLOW_PROCESS_VARIABLES.sql
@C:\PMS\PMS Dev Files\Source\Tables\FLOW_STEP_EVENT_LOG.sql
@C:\PMS\PMS Dev Files\Source\Tables\FLOW_SUBFLOWS.sql
@C:\PMS\PMS Dev Files\Source\Tables\FLOW_SUBFLOW_LOG.sql
@C:\PMS\PMS Dev Files\Source\Tables\FLOW_TIMERS.sql
@C:\PMS\PMS Dev Files\Source\Tables\FLOW_VARIABLE_EVENT_LOG.sql
@C:\PMS\PMS Dev Files\Source\Tables\HISTORY.sql
@C:\PMS\PMS Dev Files\Source\Tables\HTMLDB_PLAN_TABLE.sql
@C:\PMS\PMS Dev Files\Source\Tables\LGS_CONTRACTS.sql
@C:\PMS\PMS Dev Files\Source\Tables\LGS_CONTRACTS_TMP.sql
@C:\PMS\PMS Dev Files\Source\Tables\LGS_CONTRACT_DOCS.sql
@C:\PMS\PMS Dev Files\Source\Tables\LGS_DELETED_CONTRACTS.sql
@C:\PMS\PMS Dev Files\Source\Tables\LGS_DELETED_PROJECTS.sql
@C:\PMS\PMS Dev Files\Source\Tables\LGS_LOGOS_BRANCHES.sql
@C:\PMS\PMS Dev Files\Source\Tables\LGS_PIP_WF_DOCS.sql
@C:\PMS\PMS Dev Files\Source\Tables\LGS_PROJECTS.sql
@C:\PMS\PMS Dev Files\Source\Tables\MODULES.sql
@C:\PMS\PMS Dev Files\Source\Tables\MYIMAGES_COLLECTION.sql
@C:\PMS\PMS Dev Files\Source\Tables\MYIMAGES_TBL.sql
@C:\PMS\PMS Dev Files\Source\Tables\NEXMO_SMS_RESPONSE.sql
@C:\PMS\PMS Dev Files\Source\Tables\OPPORTUNITIES.sql
@C:\PMS\PMS Dev Files\Source\Tables\OPP_ACTIONS.sql
@C:\PMS\PMS Dev Files\Source\Tables\OPP_ACTIONS_DOCS.sql
@C:\PMS\PMS Dev Files\Source\Tables\OPP_ACTION_STAKEHOLDERS.sql
@C:\PMS\PMS Dev Files\Source\Tables\OPP_CONTACTS.sql
@C:\PMS\PMS Dev Files\Source\Tables\OPP_PRESALE_ACTIVITIES.sql
@C:\PMS\PMS Dev Files\Source\Tables\OPP_ROLE.sql
@C:\PMS\PMS Dev Files\Source\Tables\OPP_SCOPE.sql
@C:\PMS\PMS Dev Files\Source\Tables\OPP_STAGES.sql
@C:\PMS\PMS Dev Files\Source\Tables\OPP_STAGES_STATUS.sql
@C:\PMS\PMS Dev Files\Source\Tables\OPP_STATUS.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_COMPANY_CONTRACTS.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_CONTRACT_STAGES.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_CONTRACT_SUMMARY.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_CONTRACT_TYPES.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_CURRENCIES.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_CURRENCY_RATES.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_DELETED_ENROLLED_DETS.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_DELETED_ESTIMATED_DETS.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_DELETED_PRJ_WORK_TYPES.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_DURATION_UOM.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_EMPLOYEE_SALARY.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_EMPLOYEE_SALARY_HISTORY.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_EMPLOYEE_SKILLS.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_ENROLLED_DETS.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_ENROLLED_DETS_BAK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_ENROLLED_DETS_BAK1.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_ENROLLED_FILES.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_ESTIMATED_DETS.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_EXPENCES.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_EXPENCE_TYPES.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_GRADE_PRICES.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_GROUPS.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_GROUP_EMPLOYEES.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_INTERNAL_CLASSIFICATION.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_INVOICES.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_LVL_USAGE_TYPE.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_OFFER_STATUS.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_OUTCOME_TYPES.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_PARAMETERS.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_PIPELINE_MODULES.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_PROJECTWORK_TYPES.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_PROJECT_STATUS_HISTORY.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_PROJECT_TEMPLATES.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_PROJECT_TEMPLATE_DETS.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_PRWKTP_DET_STATUS.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_PRWKTP_DET_TYPES.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_SALARY_GRADES.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_SALARY_GRADES_HISTORY.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_STATUS.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_TASKS.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_USER_CONTRACTS.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_ASSIGNEES.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_DEPENDENCIES.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_DOCS.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_OUTCOMES.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WORK_TYPES.sql
@C:\PMS\PMS Dev Files\Source\Tables\PROJECT_EMPLOYEE.sql
@C:\PMS\PMS Dev Files\Source\Tables\ROLES.sql
@C:\PMS\PMS Dev Files\Source\Tables\TAREIF.sql
@C:\PMS\PMS Dev Files\Source\Tables\VLT_SMS.sql
@C:\PMS\PMS Dev Files\Source\Tables\WORK_TYPE_GROUPS.sql
@C:\PMS\PMS Dev Files\Source\Tables\XLIB_COMPONENTS.sql
@C:\PMS\PMS Dev Files\Source\Tables\XLIB_LOGS.sql
@C:\PMS\PMS Dev Files\Source\Tables\DEMO_ORDER_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\LGS_CONTRACTS_INNN.sql
@C:\PMS\PMS Dev Files\Source\Tables\CSS_TASK_IND.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_CONTRACT_STAGES_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_ENROLLED_DETS_IND_F.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_I2.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_OUTCOMES_I2.sql
@C:\PMS\PMS Dev Files\Source\Tables\CITIZEN_EVENTS_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRCS_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\OBAT_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\CSS_MOD_IND.sql
@C:\PMS\PMS Dev Files\Source\Tables\DEMO_CUST_NAME_IX.sql
@C:\PMS\PMS Dev Files\Source\Tables\XLIB_LOGS_IDX1.sql
@C:\PMS\PMS Dev Files\Source\Tables\LGS_LOGOS_BRANCHES_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_CURRENCY_RATES_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\WRKTYP_UK.sql
@C:\PMS\PMS Dev Files\Source\Tables\XLIB_LOGS_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\TIMR_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\EXPE_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\DEMO_ORDER_ITEMS_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PROJ_CONT_FK_I.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_PIPELINE_MODULES_INDEX1.sql
@C:\PMS\PMS Dev Files\Source\Tables\XLIB_LOGS_IDX2.sql
@C:\PMS\PMS Dev Files\Source\Tables\LGS_CONTRACT_DOCS_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\OPP_ROLES_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\MYIMAGES_TBL_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\CSS_EMP_IND.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_ASSIGNEES_WBA_ID_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\CONT_COMP_FK_I.sql
@C:\PMS\PMS Dev Files\Source\Tables\WRKTYP_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_ASSIGNEES_I3.sql
@C:\PMS\PMS Dev Files\Source\Tables\OPP_ACTION_STAKEHOLDERS_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_OUTCOMES_WBO_ID_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_ESTIMATED_DETS_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_DOCS_I2.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_EMPLOYEE_SKILLS_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_GROUPS_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\FMSG_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_DEPENDENCIES_I3.sql
@C:\PMS\PMS Dev Files\Source\Tables\GRDPR_UK.sql
@C:\PMS\PMS Dev Files\Source\Tables\OPP_ACTIONS_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\OPP_STATUS_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_STATUS_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\OPP_ROLE_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_ROW_KEY_UNQ.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_CONTRACT_SUMMARY_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_OFFER_STATUS_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_DEPENDENCI_ROW_KEY_UNQ.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_DOCS_WBC_ID_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\SALGRD_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_EXPENCES_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\CONN_UK.sql
@C:\PMS\PMS Dev Files\Source\Tables\DEMO_IMAGES_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\SALGRD_GRDPR_FK_I.sql
@C:\PMS\PMS Dev Files\Source\Tables\HISTORY_IDX1.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_ASSIGNEES_I4.sql
@C:\PMS\PMS Dev Files\Source\Tables\DEMO_PAGE_HIERARCHY_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_CONTRACT_TYPES_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_DEPENDENCIES_I1.sql
@C:\PMS\PMS Dev Files\Source\Tables\DEMO_USERS_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_DEPENDENCIES_I2.sql
@C:\PMS\PMS Dev Files\Source\Tables\PROJ_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\HISTORY_IDX2.sql
@C:\PMS\PMS Dev Files\Source\Tables\OBJT_UK.sql
@C:\PMS\PMS Dev Files\Source\Tables\OPP_PRESALE_ACTIVITIES_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\DGRM_UK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_I1.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_OUTCOME_TYPES_POT_ID_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\DEMO_CUSTOMERS_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_GROUP_EMPLOYEES_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_DEPENDENCI_WBD_ID_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\GRDPR_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_PRWKTP_DET_STATUS_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\XLIB_COMPONENTS_U01.sql
@C:\PMS\PMS Dev Files\Source\Tables\OPP_CONTACTS_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\EMPSAL_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\DISPLAY_ORDER_UK1.sql
@C:\PMS\PMS Dev Files\Source\Tables\SBFL_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_INVOICES_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\EXPR_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\CFIG_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_ENROLLED_DETS_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_PROJECT_STATUS_HISTORY_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_OUTCOMES_I1.sql
@C:\PMS\PMS Dev Files\Source\Tables\DEMO_PRODUCT_INFO_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\CONT_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_ESTIMATED_DETS_IND_F1.sql
@C:\PMS\PMS Dev Files\Source\Tables\OPP_SCOPE_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_OUTCOMES_ROW_KEY_UNQ.sql
@C:\PMS\PMS Dev Files\Source\Tables\TIMR_PRCS_SBFL_IX.sql
@C:\PMS\PMS Dev Files\Source\Tables\CSS_TEMP_COMPANIES_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_DOCS_I1.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_ASSIGNEES_I2.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_DOCS_ROW_KEY_UNQ.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_LVL_USAGE_TYPE_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\XLIB_COMPONENTS_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\EXPR_UK.sql
@C:\PMS\PMS Dev Files\Source\Tables\DEMO_ORD_CUSTOMER_IX.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_CURRENCIES_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJWORK_WRKTYP_FK_I.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_PRWKTP_DET_TYPES_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\CONN_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\CSS_TEMP_MODULES_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\STAGES_STATUS_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\EMPSAL_SALGRD_FK_I.sql
@C:\PMS\PMS Dev Files\Source\Tables\INDEX1.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_ASSIGNEES_ROW_KEY_UNQ.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_WBS_WBS_ID_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\OBJT_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\CSS_COMP_IND.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_ESTIMATED_DETS_IND11.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_EXPENCE_TYPES_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\OPP_STAGES_1.sql
@C:\PMS\PMS Dev Files\Source\Tables\CSS_TEMP_TASKS_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_INTERNAL_CLASSIFICATIO_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\MYIMAGES_COLLECTION_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\OPPORTUNITIES_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\DGRM_UK2.sql
@C:\PMS\PMS Dev Files\Source\Tables\CSS_TASK_COMP_MOD.sql
@C:\PMS\PMS Dev Files\Source\Tables\OPP_ACTION_STAKEHOLDERS_ACTION.sql
@C:\PMS\PMS Dev Files\Source\Tables\PROV_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJWORK_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\OPP_ACTIONS_DOCS_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJ_OUTCOME_TYPES_ROW_KEY_UNQ.sql
@C:\PMS\PMS Dev Files\Source\Tables\DGRM_PK.sql
@C:\PMS\PMS Dev Files\Source\Tables\PRJWORK_PROJ_FK_I.sql
