--------------------------------------------------------
--  DDL for Table LGS_CONTRACT_DOCS
--------------------------------------------------------

  CREATE TABLE "PRJ"."LGS_CONTRACT_DOCS" 
   (	"LCD_ID" NUMBER, 
	"LCD_FILE_NAME" VARCHAR2(200 BYTE), 
	"LCD_FILE_DESC" VARCHAR2(2000 BYTE), 
	"LCD_CNT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
