--------------------------------------------------------
--  DDL for Table LGS_DELETED_PROJECTS
--------------------------------------------------------

  CREATE TABLE "PRJ"."LGS_DELETED_PROJECTS" 
   (	"L_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"ID" NUMBER(8,0), 
	"DSP_CODE" VARCHAR2(100 BYTE), 
	"END_DATE" DATE, 
	"START_DATE" DATE, 
	"CONTRACT_ID" NUMBER(8,0), 
	"INT_CODE" VARCHAR2(50 BYTE), 
	"MODULE" VARCHAR2(200 CHAR), 
	"NEW_IMPLEMENTATION" VARCHAR2(1 BYTE), 
	"MAINTENANCE" VARCHAR2(1 BYTE), 
	"PRICING_DATE" DATE, 
	"ACTIVE" VARCHAR2(1 BYTE), 
	"SEQ" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
