--------------------------------------------------------
--  DDL for Table LGS_DELETED_CONTRACTS
--------------------------------------------------------

  CREATE TABLE "PRJ"."LGS_DELETED_CONTRACTS" 
   (	"ID" NUMBER(8,0), 
	"DSP_CODE" VARCHAR2(100 BYTE), 
	"COMPANY_CODE" VARCHAR2(5 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"USD_VALUE" NUMBER(19,0), 
	"FINALIZED" VARCHAR2(1 BYTE), 
	"CONTRACT_TYPE_ID" NUMBER(8,0), 
	"CONTRACT_STAGE_ID" NUMBER(8,0), 
	"DISPLAY_IN_CONTRACTS" VARCHAR2(1 BYTE), 
	"PRICING_DATE" DATE, 
	"PERDIUM" NUMBER(12,3), 
	"DAYS_PER_TICKET" NUMBER, 
	"TICKET_VALUE" NUMBER(12,3), 
	"HOTEL_RATE" NUMBER(12,3), 
	"CAR_RENTAL_PER_DAY" NUMBER(12,3), 
	"INTERNATIONAL" VARCHAR2(1 CHAR), 
	"WHO_CREATED" VARCHAR2(75 BYTE), 
	"DATE_DELETED" DATE, 
	"WHO_DELETED" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
