--------------------------------------------------------
--  DDL for Table LGS_CONTRACTS_TMP
--------------------------------------------------------

  CREATE TABLE "PRJ"."LGS_CONTRACTS_TMP" 
   (	"DSP_CODE" VARCHAR2(50 BYTE), 
	"COMPANY_CODE" VARCHAR2(5 BYTE), 
	"USD_VALUE" NUMBER, 
	"CONTRACT_TYPE_ID" NUMBER, 
	"CONTRACT_STAGE_ID" NUMBER, 
	"WHO_CREATED" VARCHAR2(75 BYTE), 
	"ACCOUNT_MANAGER" VARCHAR2(2000 BYTE), 
	"USAGE_TYPE" NUMBER, 
	"PROJECT_NAME" VARCHAR2(4000 BYTE), 
	"REF_INTERNAL" VARCHAR2(2000 BYTE), 
	"INVOICED_DAYS" NUMBER, 
	"EXPECTED_DELIVERY_DATE" VARCHAR2(30 BYTE), 
	"WARRANTY_IN_MONTH" NUMBER, 
	"VALUE_IN_MAINTENANCE" NUMBER, 
	"SIGNATURE_DATE" VARCHAR2(30 BYTE), 
	"OFFER_STATUS" NUMBER, 
	"REMARKS" VARCHAR2(4000 BYTE), 
	"EXPECTED_DELIVERY_NUM_OF_DAYS" NUMBER, 
	"ACCEPTANCE_DATE" VARCHAR2(30 BYTE), 
	"DELIVERY_DATE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
