--------------------------------------------------------
--  DDL for Table LGS_PROJECTS
--------------------------------------------------------

  CREATE TABLE "PRJ"."LGS_PROJECTS" 
   (	"L_DESCRIPTION" VARCHAR2(1000 BYTE), 
	"ID" NUMBER(8,0), 
	"DSP_CODE" VARCHAR2(1000 BYTE), 
	"END_DATE" DATE, 
	"START_DATE" DATE, 
	"CONTRACT_ID" NUMBER(8,0), 
	"INT_CODE" VARCHAR2(1000 BYTE), 
	"MODULE" VARCHAR2(35 CHAR), 
	"NEW_IMPLEMENTATION" VARCHAR2(1 BYTE), 
	"MAINTENANCE" VARCHAR2(1 BYTE), 
	"PRICING_DATE" DATE, 
	"ACTIVE" VARCHAR2(1 BYTE), 
	"SEQ" NUMBER, 
	"HIGH_LEVEL_ESTIMATE" NUMBER, 
	"HIGH_LEVEL_REMAINING" NUMBER, 
	"STATUS" NUMBER, 
	"IS_INVOICED_FLG" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"APPROVAL_DATE" DATE, 
	"PAYMENT_PERCENTAGE" NUMBER, 
	"AMOUNT" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
