--------------------------------------------------------
--  DDL for Table LGS_PIP_WF_DOCS
--------------------------------------------------------

  CREATE TABLE "PRJ"."LGS_PIP_WF_DOCS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(400 BYTE), 
	"FILENAME" VARCHAR2(400 BYTE), 
	"TITLE" VARCHAR2(255 BYTE), 
	"MIME_TYPE" VARCHAR2(255 BYTE), 
	"DOC_SIZE" NUMBER, 
	"DAD_CHARSET" VARCHAR2(128 BYTE), 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"CREATED_ON" DATE, 
	"UPDATED_BY" VARCHAR2(255 BYTE), 
	"UPDATED_ON" DATE, 
	"LAST_UPDATE" DATE, 
	"CONTENT_TYPE" VARCHAR2(128 BYTE), 
	"BLOB_CONTENT" BLOB, 
	"LANGUAGE" VARCHAR2(30 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"FILE_TYPE" VARCHAR2(255 BYTE), 
	"FILE_CHARSET" VARCHAR2(128 BYTE), 
	"ACTIVITI_INSTANCE_ID" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("BLOB_CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
