--------------------------------------------------------
--  DDL for Table LGS_LOGOS_BRANCHES
--------------------------------------------------------

  CREATE TABLE "PRJ"."LGS_LOGOS_BRANCHES" 
   (	"LLB_ID" NUMBER, 
	"LLB_CODE" VARCHAR2(20 BYTE), 
	"LLB_DESC" VARCHAR2(1000 BYTE), 
	"LLB_ADDRESS" VARCHAR2(1000 BYTE), 
	"LLB_EMAIL" VARCHAR2(1000 BYTE), 
	"LLB_PHONE" VARCHAR2(20 BYTE), 
	"LLB_FAX" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
