--------------------------------------------------------
--  DDL for Table MODULES
--------------------------------------------------------

  CREATE TABLE "PRJ"."MODULES" 
   (	"CODE" VARCHAR2(5 BYTE), 
	"E_NAME" VARCHAR2(100 BYTE), 
	"A_NAME" VARCHAR2(35 BYTE), 
	"DISPLAY" NUMBER, 
	"SORTORDER" NUMBER, 
	"PARENT_CODE" VARCHAR2(5 BYTE), 
	"CURRENT_PRICE" NUMBER, 
	"CURRENCY" NUMBER, 
	"SUPPORT_FEE" NUMBER, 
	"FORSALE" VARCHAR2(1 BYTE), 
	"SUPPLIER" VARCHAR2(5 BYTE), 
	"DEFAULT_QTY" NUMBER, 
	"DISPLAY_FOR_SUPPORT" VARCHAR2(1 BYTE), 
	"DISPLAY_FOR_CUSTOMERS" VARCHAR2(1 BYTE), 
	"DISPLAY_IN_SERVERICES" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
