--------------------------------------------------------
--  DDL for Table MYIMAGES_TBL
--------------------------------------------------------

  CREATE TABLE "PRJ"."MYIMAGES_TBL" 
   (	"ID" NUMBER, 
	"IMAGE_NAME" VARCHAR2(400 BYTE), 
	"FILENAME" VARCHAR2(350 BYTE), 
	"MIME_TYPE" VARCHAR2(255 BYTE), 
	"DOC_SIZE" NUMBER, 
	"CHARSET" VARCHAR2(128 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"CONTENT" BLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
