--------------------------------------------------------
--  DDL for Table NEXMO_SMS_RESPONSE
--------------------------------------------------------

  CREATE TABLE "PRJ"."NEXMO_SMS_RESPONSE" 
   (	"RESPONSE_PK" NUMBER, 
	"STATUS" VARCHAR2(255 BYTE), 
	"MESSAGE_ID" VARCHAR2(255 BYTE), 
	"MESSAGE_TO" VARCHAR2(255 BYTE), 
	"MESSAGE_TEXT" VARCHAR2(1000 BYTE), 
	"CLIENT_REF" VARCHAR2(255 BYTE), 
	"REMAINING_BALANCE" NUMBER, 
	"MESSAGE_PRICE" NUMBER, 
	"MESSAGE_NETWORK" VARCHAR2(255 BYTE), 
	"ERROR_TEXT" VARCHAR2(1000 BYTE), 
	"CODE" VARCHAR2(20 BYTE), 
	"IP_ADDRESS" VARCHAR2(20 BYTE), 
	"PURPOSE" VARCHAR2(20 BYTE), 
	"CREATED_TIMESTAMP" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
