--------------------------------------------------------
--  DDL for Table OPP_STAGES
--------------------------------------------------------

  CREATE TABLE "PRJ"."OPP_STAGES" 
   (	"OST_CODE" NUMBER, 
	"OST_DSP_CODE" VARCHAR2(15 BYTE), 
	"OST_E_DESC" VARCHAR2(200 BYTE), 
	"OST_A_DESC" VARCHAR2(200 BYTE), 
	"OST_WEIGHT" NUMBER, 
	"OST_DISPLAY_ORDER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
