--------------------------------------------------------
--  DDL for Table OPP_ACTION_STAKEHOLDERS
--------------------------------------------------------

  CREATE TABLE "PRJ"."OPP_ACTION_STAKEHOLDERS" 
   (	"OAS_ID" NUMBER, 
	"OAS_OAC_ID" NUMBER, 
	"OAS_PRJ_CODE" VARCHAR2(20 BYTE), 
	"OAS_EMPLOYEE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
