--------------------------------------------------------
--  DDL for Table OPP_ACTIONS
--------------------------------------------------------

  CREATE TABLE "PRJ"."OPP_ACTIONS" 
   (	"OAC_ID" NUMBER, 
	"OAC_DATE" DATE, 
	"OAC_DESC" VARCHAR2(2000 BYTE), 
	"OAC_DURATION" VARCHAR2(200 BYTE), 
	"OAC_OUTPUTS" VARCHAR2(2000 BYTE), 
	"OAC_NEXT_ACTION_DESC" VARCHAR2(2000 BYTE), 
	"OAC_NEXT_ACTION_DATE" DATE, 
	"OAC_REMARKS" VARCHAR2(2000 BYTE), 
	"OAC_OPP_ID" NUMBER, 
	"OAC_OPA_ID" NUMBER, 
	"OAC_TAKEN_BY" VARCHAR2(20 BYTE), 
	"OAC_LOCATION" VARCHAR2(200 BYTE), 
	"OAC_DURATION_HOURS" NUMBER, 
	"OAC_DURATION_MINUTES" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
