--------------------------------------------------------
--  DDL for Table OPP_STATUS
--------------------------------------------------------

  CREATE TABLE "PRJ"."OPP_STATUS" 
   (	"OPS_CODE" NUMBER, 
	"OPS_DSP_CODE" VARCHAR2(5 BYTE), 
	"OPS_ENAME" VARCHAR2(135 BYTE), 
	"OPS_ANAME" VARCHAR2(135 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
