--------------------------------------------------------
--  DDL for Table PRJ_STATUS
--------------------------------------------------------

  CREATE TABLE "PRJ"."PRJ_STATUS" 
   (	"PST_ID" NUMBER, 
	"PST_CODE" VARCHAR2(200 BYTE), 
	"PST_DESC" VARCHAR2(2000 BYTE), 
	"PST_SEND_EMAIL_FLG" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
