--------------------------------------------------------
--  DDL for Table PRJ_WBS_DEPENDENCIES
--------------------------------------------------------

  CREATE TABLE "PRJ"."PRJ_WBS_DEPENDENCIES" 
   (	"PRJ_WBS_DOC_ID" NUMBER, 
	"ROW_KEY" VARCHAR2(30 BYTE), 
	"WBD_ID" NUMBER, 
	"WBD_TYPE" VARCHAR2(1 BYTE), 
	"WBD_WBS_ID" NUMBER, 
	"WBD_DEP_TASK_ID" NUMBER, 
	"CREATED" DATE, 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"UPDATED" DATE, 
	"UPDATED_BY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
