--------------------------------------------------------
--  DDL for Table PRJ_EMPLOYEE_SALARY
--------------------------------------------------------

  CREATE TABLE "PRJ"."PRJ_EMPLOYEE_SALARY" 
   (	"EMP_CODE" VARCHAR2(20 BYTE), 
	"EMP_NAME" VARCHAR2(35 BYTE), 
	"ACTIVE" VARCHAR2(1 BYTE), 
	"SALARY_GRADE_ID" NUMBER(8,0), 
	"INT_CODE" VARCHAR2(100 CHAR), 
	"CHANGE_DATE" DATE, 
	"USER_NAME" VARCHAR2(35 CHAR), 
	"PASSWRD" VARCHAR2(30 BYTE), 
	"TOBECHECKED" VARCHAR2(1 CHAR), 
	"EMP_EMAIL" VARCHAR2(100 BYTE), 
	"IS_ADMIN" VARCHAR2(1 BYTE), 
	"EMP_TITLE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
