--------------------------------------------------------
--  DDL for Index PRJ_ENROLLED_DETS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRJ"."PRJ_ENROLLED_DETS_PK" ON "PRJ"."PRJ_ENROLLED_DETS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
