--------------------------------------------------------
--  DDL for Table PRJ_WBS_DOCS
--------------------------------------------------------

  CREATE TABLE "PRJ"."PRJ_WBS_DOCS" 
   (	"PRJ_WB_ID" NUMBER, 
	"ROW_KEY" VARCHAR2(30 BYTE), 
	"WBC_ID" NUMBER, 
	"WBC_NAME" VARCHAR2(100 BYTE), 
	"WBC_DESC" VARCHAR2(1000 BYTE), 
	"WBC_PATH" VARCHAR2(200 BYTE), 
	"WBC_DOC" BLOB, 
	"WBC_DOC_FILENAME" VARCHAR2(512 BYTE), 
	"WBC_DOC_MIMETYPE" VARCHAR2(512 BYTE), 
	"WBC_DOC_CHARSET" VARCHAR2(512 BYTE), 
	"WBC_DOC_LASTUPD" DATE, 
	"WBC_WBS_ID" NUMBER, 
	"CREATED" DATE, 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"UPDATED" DATE, 
	"UPDATED_BY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("WBC_DOC") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
