--------------------------------------------------------
--  DDL for Table PRJ_CURRENCY_RATES
--------------------------------------------------------

  CREATE TABLE "PRJ"."PRJ_CURRENCY_RATES" 
   (	"ID" NUMBER(8,0), 
	"CURRENCY_ID" NUMBER(8,0), 
	"RATE" NUMBER(19,4), 
	"DAY" DATE, 
	"OLD_RATE" NUMBER(19,4), 
	"WHO_DID" VARCHAR2(75 BYTE), 
	"DATE_CHANGED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
