--------------------------------------------------------
--  DDL for Table PRJ_PROJECT_TEMPLATE_DETS
--------------------------------------------------------

  CREATE TABLE "PRJ"."PRJ_PROJECT_TEMPLATE_DETS" 
   (	"ID" NUMBER, 
	"SEQ" VARCHAR2(100 CHAR), 
	"PARENT_ID" NUMBER, 
	"DESCRIPTION" VARCHAR2(4000 CHAR), 
	"TASK_ID" NUMBER, 
	"DURATION_TAKEN" NUMBER, 
	"DURATION_UOM" NUMBER, 
	"RESOURCES" VARCHAR2(4000 CHAR), 
	"PROJECT_TEMPLATE_ID" NUMBER, 
	"ONSITEATOFFICE" VARCHAR2(1 BYTE), 
	"WHOWILLDO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
