--------------------------------------------------------
--  DDL for Table PRJ_OUTCOME_TYPES
--------------------------------------------------------

  CREATE TABLE "PRJ"."PRJ_OUTCOME_TYPES" 
   (	"ROW_KEY" VARCHAR2(30 BYTE), 
	"POT_ID" NUMBER, 
	"POT_NAME" VARCHAR2(100 BYTE), 
	"POT_DESC" VARCHAR2(200 BYTE), 
	"CREATED" DATE, 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"UPDATED" DATE, 
	"UPDATED_BY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
