--------------------------------------------------------
--  DDL for Table PRJ_DELETED_PRJ_WORK_TYPES
--------------------------------------------------------

  CREATE TABLE "PRJ"."PRJ_DELETED_PRJ_WORK_TYPES" 
   (	"ID" NUMBER(8,0), 
	"GRADE" NUMBER(8,2), 
	"ESTIMATED_DAYS" NUMBER(8,2), 
	"ENROLLED_DAYS" NUMBER(8,2), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"WRKTYP_ID" NUMBER(8,0), 
	"PROJ_ID" NUMBER(8,0), 
	"QTY" NUMBER(4,0), 
	"SEQ" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
