--------------------------------------------------------
--  DDL for Table PRJ_SALARY_GRADES
--------------------------------------------------------

  CREATE TABLE "PRJ"."PRJ_SALARY_GRADES" 
   (	"ID" NUMBER(8,0), 
	"FROM_SALARY" NUMBER(8,2), 
	"TO_SALARY" NUMBER(8,2), 
	"GRADE_PRICE_ID" NUMBER(8,0), 
	"UNITS" NUMBER(5,2), 
	"NAME" VARCHAR2(35 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
