--------------------------------------------------------
--  DDL for Table PRJ_WBS_OUTCOMES
--------------------------------------------------------

  CREATE TABLE "PRJ"."PRJ_WBS_OUTCOMES" 
   (	"PRJ_WBS_ASSIGNEE_ID" NUMBER, 
	"ROW_KEY" VARCHAR2(30 BYTE), 
	"WBO_ID" NUMBER, 
	"WBO_OUTCOME" BLOB, 
	"WBO_OUTCOME_FILENAME" VARCHAR2(512 BYTE), 
	"WBO_OUTCOME_MIMETYPE" VARCHAR2(512 BYTE), 
	"WBO_OUTCOME_CHARSET" VARCHAR2(512 BYTE), 
	"WBO_OUTCOME_LASTUPD" DATE, 
	"WBO_DESC" VARCHAR2(100 BYTE), 
	"WBO_POT_ID" NUMBER, 
	"WBO_TO_CHANGE" VARCHAR2(1000 BYTE), 
	"CREATED" DATE, 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"UPDATED" DATE, 
	"UPDATED_BY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("WBO_OUTCOME") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
