--------------------------------------------------------
--  DDL for Table PRJ_WBS_ASSIGNEES
--------------------------------------------------------

  CREATE TABLE "PRJ"."PRJ_WBS_ASSIGNEES" 
   (	"ROW_KEY" VARCHAR2(30 BYTE), 
	"WBA_ID" NUMBER, 
	"WBA_TASK_ID" NUMBER, 
	"WBA_EMP_ID" VARCHAR2(100 BYTE), 
	"WBA_STATUS" NUMBER, 
	"WBA_START_DATE" DATE, 
	"WBA_END_DATE" DATE, 
	"WBA_COMPLEATION_PERCENTAGE" NUMBER, 
	"WBA_ISRF" BLOB, 
	"WBA_ISRF_FILENAME" VARCHAR2(512 BYTE), 
	"WBA_ISRF_MIMETYPE" VARCHAR2(512 BYTE), 
	"WBA_ISRF_CHARSET" VARCHAR2(512 BYTE), 
	"WBA_ISRF_LASTUPD" DATE, 
	"CREATED" DATE, 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"UPDATED" DATE, 
	"UPDATED_BY" VARCHAR2(255 BYTE), 
	"WBA_EST_DET_ID" NUMBER, 
	"WBA_SUBJECT" VARCHAR2(100 BYTE), 
	"WBA_TEXT" VARCHAR2(2000 BYTE), 
	"WBA_PRIORITY" NUMBER, 
	"WBA_ISRF_CODE" VARCHAR2(20 BYTE), 
	"WBA_NUM_OF_HOURS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("WBA_ISRF") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
