--------------------------------------------------------
--  DDL for Table PRJ_WORK_TYPES
--------------------------------------------------------

  CREATE TABLE "PRJ"."PRJ_WORK_TYPES" 
   (	"ID" NUMBER(8,0), 
	"E_NAME" VARCHAR2(135 BYTE), 
	"A_NAME" VARCHAR2(135 BYTE), 
	"FROM_GRADE" NUMBER(8,2), 
	"TO_GRADE" NUMBER(8,2) DEFAULT 0, 
	"INT_CODE" VARCHAR2(15 BYTE), 
	"SEQ" NUMBER, 
	"NEW_IMPLEMENTATION" VARCHAR2(1 BYTE), 
	"MAINTENANCE" VARCHAR2(1 BYTE), 
	"SUPPORT" VARCHAR2(1 BYTE), 
	"TOBECHECKED" VARCHAR2(1 CHAR), 
	"WORK_TYPE_GROUP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
