--------------------------------------------------------
--  DDL for Table PRJ_COMPANY_CONTRACTS
--------------------------------------------------------

  CREATE TABLE "PRJ"."PRJ_COMPANY_CONTRACTS" 
   (	"ID" NUMBER, 
	"COMPANY_CODE" VARCHAR2(13 CHAR), 
	"CUSTOMER_CODE_CSS" VARCHAR2(50 CHAR), 
	"CUSTOMER_NAME_CSS" VARCHAR2(220 CHAR), 
	"MIN_DAY" DATE, 
	"CREATE_CONTRACT" VARCHAR2(1 CHAR), 
	"DATE_UPDATED" DATE, 
	"WHO_UPDATED" VARCHAR2(400 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
