--------------------------------------------------------
--  DDL for Table PRJ_GRADE_PRICES
--------------------------------------------------------

  CREATE TABLE "PRJ"."PRJ_GRADE_PRICES" 
   (	"ID" NUMBER(8,0), 
	"DSP_CODE" VARCHAR2(25 BYTE), 
	"E_NAME" VARCHAR2(135 BYTE), 
	"A_NAME" VARCHAR2(135 BYTE), 
	"UNIT_PRICE" NUMBER(8,2), 
	"START_DATE" DATE, 
	"END_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
