--------------------------------------------------------
--  DDL for Table PRJ_EXPENCES
--------------------------------------------------------

  CREATE TABLE "PRJ"."PRJ_EXPENCES" 
   (	"ID" NUMBER(8,0), 
	"CONTRACT_ID" NUMBER, 
	"PROJECT_ID" NUMBER, 
	"TASK_ID" NUMBER, 
	"EMPLOYEE_CODE" VARCHAR2(13 BYTE), 
	"EXPENCE_TYPE_ID" NUMBER, 
	"DAY" DATE, 
	"AMOUNT" NUMBER(19,4), 
	"CURRENCY" NUMBER, 
	"RATE" NUMBER(19,4), 
	"NOTES" VARCHAR2(2000 BYTE), 
	"MODULE" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
