--------------------------------------------------------
--  DDL for Table XLIB_COMPONENTS
--------------------------------------------------------

  CREATE TABLE "PRJ"."XLIB_COMPONENTS" 
   (	"COMP_ID" NUMBER, 
	"COMP_NAME" VARCHAR2(100 CHAR), 
	"COMP_VERSION" VARCHAR2(50 CHAR), 
	"COMP_VERSION_LABEL" VARCHAR2(50 CHAR), 
	"COMP_DEPENDS_ON" VARCHAR2(4000 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
