--------------------------------------------------------
--  DDL for Table XLIB_LOGS
--------------------------------------------------------

  CREATE TABLE "PRJ"."XLIB_LOGS" 
   (	"LOG_ID" NUMBER, 
	"LOG_MODULE" VARCHAR2(100 CHAR), 
	"LOG_MSG" VARCHAR2(4000 CHAR), 
	"LOG_TYPE" VARCHAR2(20 CHAR) DEFAULT 'DEBUG', 
	"LOG_LEVEL" NUMBER DEFAULT 15, 
	"LOG_CREATED_ON" DATE, 
	"LOG_CREATED_BY" VARCHAR2(30 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
