--------------------------------------------------------
--  DDL for Procedure INSERT_LGS_CONTRACT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PRJ"."INSERT_LGS_CONTRACT" (
PROJECT_NAME_P varchar2, DSP_CODE_P varchar2 , 
REF_INTERNAL_P varchar2, SIGNATURE_DATE_P VARCHAR2, 
INVOICED_DAYS_P varchar2, EXPECTED_DELIVERY_DATE_P VARCHAR2, 
DELIVERY_DATE_P VARCHAR2, WARRANTY_IN_MONTH_P varchar2,
USD_VALUE_P varchar2, ACCEPTANCE_DATE_P VARCHAR2, 
VALUE_IN_MAINTENANCE_P varchar2, 
REMARKS_P varchar2, CONTRACT_TYPE_ID_P varchar2,
 ACCOUNT_MANAGER_P varchar2, COMPANY_CODE_P  varchar2, 
 OFFER_STATUS_P varchar2, CONTRACT_STAGE_ID_P varchar2,
 USAGE_TYPE_P varchar2 )
as
begin
insert into lgs_contracts(DSP_CODE ,COMPANY_CODE, USD_VALUE , 
CONTRACT_TYPE_ID,
CONTRACT_STAGE_ID, 
WHO_CREATED,  ACCOUNT_MANAGER, 
USAGE_TYPE , 
PROJECT_NAME,
REF_INTERNAL ,INVOICED_DAYS  ,
EXPECTED_DELIVERY_DATE ,WARRANTY_IN_MONTH ,
VALUE_IN_MAINTENANCE,
SIGNATURE_DATE ,
OFFER_STATUS ,
REMARKS ,ACCEPTANCE_DATE, DELIVERY_DATE)
 
values (DSP_CODE_P ,COMPANY_CODE_P, to_number(USD_VALUE_P,'999999'),
to_number(CONTRACT_TYPE_ID_P,'999999'),
to_number(CONTRACT_STAGE_ID_P,'999999'), 
ACCOUNT_MANAGER_P,  ACCOUNT_MANAGER_P, 
to_number(USAGE_TYPE_P,'999999') , 
PROJECT_NAME_P,
REF_INTERNAL_P, to_number(INVOICED_DAYS_P,'999999')  ,
TO_DATE(to_char(EXPECTED_DELIVERY_DATE_P,'YYYY/MM/DD')) ,to_number(WARRANTY_IN_MONTH_P,'999999') ,
to_number(VALUE_IN_MAINTENANCE_P,'999999'), 
TO_DATE(to_char(SIGNATURE_DATE_P,'YYYY/MM/DD')) ,
to_number(OFFER_STATUS_P,'999999') ,
REMARKS_P ,TO_DATE(to_char(ACCEPTANCE_DATE_P,'YYYY/MM/DD')), TO_DATE(to_char(DELIVERY_DATE_P,'YYYY/MM/DD')));

commit;
end;

/
