--------------------------------------------------------
--  DDL for Procedure UPDATE_PIP_CONT_ACTIVITI
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PRJ"."UPDATE_PIP_CONT_ACTIVITI" 
(p_ID	 NUMBER,
p_DSP_CODE	VARCHAR2,
p_COMPANY_CODE	VARCHAR2	,
p_START_DATE	DATE	,
p_END_DATE	DATE	,
p_USD_VALUE	  NUMBER	,
p_FINALIZED	VARCHAR2	,
p_CONTRACT_TYPE_ID	NUMBER	,
p_CONTRACT_STAGE_ID	NUMBER	,
p_DISPLAY_IN_CONTRACTS	VARCHAR2,
p_PRICING_DATE  	DATE	,
p_PERDIUM	NUMBER	,
p_DAYS_PER_TICKET	NUMBER	,
p_TICKET_VALUE	NUMBER	,
p_HOTEL_RATE	NUMBER	,
p_CAR_RENTAL_PER_DAY   NUMBER,
p_INTERNATIONAL	  VARCHAR2	,
p_WHO_CREATED	 VARCHAR2	,
p_ACCOUNT_MANAGER	     VARCHAR2	,
p_PARENT_CONTRACT	NUMBER	,
p_PROJECT_NAME	  VARCHAR2	,
p_REF_PM	  VARCHAR2,
p_REF_INTERNAL	   VARCHAR2,
p_INHOUSE_RATE	NUMBER	,
p_ONSITE_RATE	NUMBER	,
p_IN_SCOPE	NUMBER	,
p_INVOICED_DAYS	 NUMBER	,
p_INITIAL_AMOUNT	  NUMBER	,
p_DISCOUNT_IN_DAYS	 NUMBER	,
p_DISCOUNT_IN_AMOUNT  	NUMBER	,
p_VAT_VALUE	  NUMBER	,
p_FINAL_AMOUNT	NUMBER	,
p_EXPECTED_DEL_DATE	DATE	,
p_WARRANTY_IN_MONTH	NUMBER	,
p_VALUE_IN_MAINTENANCE	NUMBER	,
p_SIGNATURE_DATE	DATE	,
p_SIGNED_BY	  VARCHAR2,
p_PAYMENT_TERM	VARCHAR2,
p_REMARKS	VARCHAR2,
p_OTHER_EXPENSES_ON_CLIENT	  NUMBER	,
p_SETTLED	  NUMBER,
p_IH_INVOICE_DAYS	  NUMBER	,
p_AS_INVOICE_DAYS	    NUMBER	,
p_IH_INITIAL_AMOUNT	 NUMBER	,
p_AS_INITIAL_AMOUNT  	NUMBER	,
p_INTERNAL_CLASSIFICATION	NUMBER,
p_APPROVAL_DATE	    DATE	,
p_BRANCH_ID	   NUMBER	,
p_RFP_FILES	VARCHAR2	,
p_RESPONSE_TO_RFP_FILES	VARCHAR2	,
p_DESCRIPTION	  VARCHAR2	,
p_REFERENCES	    VARCHAR2	,
p_CLIENT_SIGNATURE_NAME	  VARCHAR2	,
p_CLIENT_SIGNATURE_DATE  	DATE	,
p_EXPECTED_DEL_DAYS	 number,
p_LL_VALUE	NUMBER	,
p_ACCEPTANCE_DATE	DATE	,
p_DELIVERY_DATE	date ,
p_APPLICENSE NUMBER,
p_ORACLELICENSE NUMBER
)

is

v_1 number ;

begin
   select nvl(REF_TO_PIPELINE,REF_TO_CONTRACT)   into v_1 
   from lgs_contracts
   where id = p_id;
   
update lgs_contracts
set DSP_CODE = p_DSP_CODE		,
USD_VALUE	= p_USD_VALUE	,
PRICING_DATE = to_date( p_PRICING_DATE	,'dd/mm/yyyy')		,
REF_PM =  p_REF_PM		,
INHOUSE_RATE = 	p_INHOUSE_RATE	,
ONSITE_RATE	= p_ONSITE_RATE	,
IN_SCOPE = p_IN_SCOPE	,
INVOICED_DAYS	=	p_INVOICED_DAYS,
INITIAL_AMOUNT	= p_INITIAL_AMOUNT	,
DISCOUNT_IN_DAYS	= p_DISCOUNT_IN_DAYS,
DISCOUNT_IN_AMOUNT	 = p_DISCOUNT_IN_AMOUNT	,
VAT_VALUE = p_VAT_VALUE		,
FINAL_AMOUNT    =   p_FINAL_AMOUNT	,
EXPECTED_DELIVERY_DATE = to_date(p_EXPECTED_DEL_DATE	,'dd/mm/yyyy')	,
WARRANTY_IN_MONTH	= p_WARRANTY_IN_MONTH	,
VALUE_IN_MAINTENANCE = p_VALUE_IN_MAINTENANCE		,
SIGNATURE_DATE	= to_date(p_SIGNATURE_DATE	,'dd/mm/yyyy'), 
SIGNED_BY = p_SIGNED_BY	,
PAYMENT_TERM = p_PAYMENT_TERM	,
REMARKS = p_REMARKS	,	
OTHER_EXPENSES_ON_CLIENT = p_OTHER_EXPENSES_ON_CLIENT		,
CLIENT_SIGNATURE_NAME =  p_CLIENT_SIGNATURE_NAME	,
CLIENT_SIGNATURE_DATE =to_date(p_CLIENT_SIGNATURE_DATE	,'dd/mm/yyyy')	,
EXPECTED_DELIVERY_NUM_OF_DAYS = p_EXPECTED_DEL_DAYS,
LL_VALUE   =   p_LL_VALUE,
APP_LICENSE = p_APPLICENSE ,
ORACLE_LICENSE= p_ORACLELICENSE
where id = v_1; 

EXCEPTION 
   WHEN   others  THEN 
   null;

end;

/
